---
- name: "Inspect VMs"
  hosts: "kubernetes"
  remote_user: "{{ ansible_ssh_remote_user }}"
  gather_facts: 'false'
  tasks:
    - name: "Collect VMs"
      community.general.proxmox_kvm:
        state: "current"
        node: "{{ proxmox_api_node }}"
        name: "{{ inventory_hostname }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
      delegate_to: localhost
      register: vm_state

    - name: "Print current VM state."
      ansible.builtin.debug:
        msg: "{{ vm_state.msg }}"
