---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: node-collector
  name: node-collector
  namespace: checkmk-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checkmk-node-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkmk-collectors-podsecurity
subjects:
  - kind: ServiceAccount
    name: node-collector
    namespace: checkmk-monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  labels:
    app: node-collector-container-metrics
  name: node-collector-container-metrics
  namespace: checkmk-monitoring
spec:
  selector:
    matchLabels:
      app: node-collector-container-metrics
      name: node-collector-container-metrics
  template:
    metadata:
      labels:
        app: node-collector-container-metrics
        name: node-collector-container-metrics
    spec:
      containers:
        - image: checkmk/kubernetes-collector:main_<YYYY.MM.DD>
          imagePullPolicy: Always
          name: container-metrics-collector
          volumeMounts:
            - name: checkmk-ca-cert
              mountPath: /etc/ca-certificates/checkmk-ca-cert.pam
              subPath: checkmk-ca-cert.pam
              readOnly: true
          command:
            - "/usr/local/bin/checkmk-container-metrics-collector"
          args:
            - "--secure-protocol"
            - "--verify-ssl"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 150m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
      serviceAccountName: node-collector
      terminationGracePeriodSeconds: 30
      volumes:
        - name: checkmk-ca-cert
          secret:
            secretName: cluster-collector-secret
            items:
              - key: checkmk-ca-cert
                path: checkmk-ca-cert.pam
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  labels:
    app: node-collector-machine-sections
  name: node-collector-machine-sections
  namespace: checkmk-monitoring
spec:
  selector:
    matchLabels:
      app: node-collector-machine-sections
      name: node-collector-machine-sections
  template:
    metadata:
      labels:
        app: node-collector-machine-sections
        name: node-collector-machine-sections
    spec:
      containers:
        - image: checkmk/kubernetes-collector:main_<YYYY.MM.DD>
          imagePullPolicy: Always
          name: machine-sections-collector
          volumeMounts:
            - name: checkmk-ca-cert
              mountPath: /etc/ca-certificates/checkmk-ca-cert.pam
              subPath: checkmk-ca-cert.pam
              readOnly: true
          command:
            - "/usr/local/bin/checkmk-machine-sections-collector"
          args:
            - "--secure-protocol"
            - "--verify-ssl"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 150m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
      serviceAccountName: node-collector
      terminationGracePeriodSeconds: 30
      volumes:
        - name: checkmk-ca-cert
          secret:
            secretName: cluster-collector-secret
            items:
              - key: checkmk-ca-cert
                path: checkmk-ca-cert.pam
